apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  labels:
    app: flaskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
        - name: flaskapp
          image: vishnukrajan007/flaskapp:latest  # Updated via Jenkins
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
